# Generated by Django 5.2 on 2025-05-04 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('read', 'Прочитано'), ('reading', 'Читается'), ('borrowed', 'Одолжено')], default='reading', max_length=20)),
                ('genre', models.CharField(choices=[('classic', 'Классика'), ('fantasy', 'Фэнтези'), ('novel', 'Романы'), ('horror', 'Ужасы'), ('adventure', 'Приключения'), ('humor', 'Юмор'), ('biography', 'Биографии'), ('history', 'История'), ('science', 'Наука/Техника')], default='novel', max_length=50)),
                ('ISBN', models.CharField(blank=True, default='', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
